root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  entrypoint = ["./tmp/server"]
  delay = 1000
  exclude_dir = ["tmp", "data", "migrations"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "sql"]
  kill_delay = "0s"
  stop_on_error = true

[log]
  main_only = false
  time = false

[color]
  main = "magenta"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
